### PR TITLE
Swipe to quote message

### PR DESCRIPTION
**Pull request by Polynomdivision**
To preface this: I am not an Android dev, so this might not be as well made as expected.

This PR "fixes" #3608 by implementing a swipe to quote functionality. I may have gone overboard with this, but I implemented it
by first moving the ListView in the ConversationFragment to a RecyclerView and then using the ItemTouchHelper to allow the swiping.

It only allows quoting messages that are quotable by the context menu.

Some notes:
- The code will likely have to be cleaned up
- If this is something worth merging, maybe it would be wise to split up adding the swipe functionality and refactoring to RecyclerViews into separate PRs?
- Maybe I should remove the line that restricts the swipe, as you can see in the video that I once did not swipe far enough

https://user-images.githubusercontent.com/14260362/106364306-50ca1b00-632e-11eb-94b2-72a4a257566b.mp4

### CODE REVIEW

**Comment by licaon-kter** [comment]
Now, if you'd add user name too to the quote (in groups I mean) this would be perfect.

**Comment by iNPUTmice** [comment]
I’m going to be honest and upfront with you.
This is not going to be merged.
Conversations 2.x has reached it's end of life and Conversations 3.x will be a pretty huge refactor in everything UI related. However it is going to take a while until 3.x actually happens.
I need Conversations 2.x to be as stable as possible until then and I'm not going to merge anything that's more than a one line bug fix.

**Comment by Polynomdivision** [comment]
@iNPUTmice If it's just because of the work on Conversations 3.x, then I would be happy to refactor this PR once that release happens.

**Comment by mimi89999** [comment]
Hello,
I noticed what's probably an unintended change. In conversations with only a few messages, the messages are aligned to top and not bottom like before.

After applying this PR:
Screenshot_2021-02-10_145805

Before applying this PR:
Screenshot_2021-02-10_145815

**Pull request closed without merging**
