### PR TITLE
Update MTM to fix vulns

### PR DESCRIPTION
**Pull request by mimi89999**
https://github.com/ge0rg/MemorizingTrustManager/issues/62
https://github.com/ge0rg/MemorizingTrustManager/issues/64

### CODE REVIEW

**Comment by iNPUTmice** [comment]
Wouldn’t this prompt the user to accept an expired certificate and then not work?

**Comment by iNPUTmice** [comment]
I’m sorry I don’t get ge0rg/MemorizingTrustManager#62 Can you explain this in *a lot* more detail please?

Wouldn’t the cert be accepted by the next line anyway?

**Comment by mimi89999** [comment]
The problem is that `checkServerTrusted` can throw an expired exception even if the certificate is not in the trust store. I tested everything in the example app in MTM and now everything works correctly. Please try.

**Comment by mimi89999** [comment]
@iNPUTmice I think that your solution is not correct. In the dialog, only the CN is show, but a certificate is valid for all SANs inside it. An attacker could trick a user into accenting a certificate that has in the CN his domain, but in SANs domains of other servers. Conversations will trust this certificate for all those domains, but that would probably not be what the user intended.

**Pull request closed without merging**
