### PR TITLE
Draft: F-Droid 2.10.5 - Revert commits needing newer webrtc versions

### PR DESCRIPTION
**Pull request by licaon-kter**
Thanks

### CODE REVIEW

**Comment by iNPUTmice** [comment]
There are a few commits that are probably unrelated to the webrtc bump

* [Revert "do not restart wakelock if activity is finishing"](https://github.com/iNPUTmice/Conversations/pull/4310/commits/eb4e6f08cee2c56ab4931d588b74a988cd1a74b3)
* [Revert "show 'using account …' in incoming call screen"](https://github.com/iNPUTmice/Conversations/pull/4310/commits/942429a77e5e7ee86859bdcf59683162461eeb66)
* [Revert "show jid only for incoming calls during ringing"](https://github.com/iNPUTmice/Conversations/pull/4310/commits/37c7e5ca80d9b4335d3f383d9d7f2a49fdba02eb)

**Comment by licaon-kter** [comment]
> Revert "do not restart wakelock if activity is finishing"

Depends on https://github.com/iNPUTmice/Conversations/commit/9c3f55bef220351e5eff5790b38ccec93aa6c573 which depends on https://github.com/iNPUTmice/Conversations/commit/61851e5f843307f2f90de892fd4fefbff5b19d46 and so on...

**Comment by licaon-kter** [comment]
> [Revert "show 'using account …' in incoming call screen"](https://github.com/iNPUTmice/Conversations/pull/4310/commits/942429a77e5e7ee86859bdcf59683162461eeb66)
> [Revert "show jid only for incoming calls during ringing"](https://github.com/iNPUTmice/Conversations/pull/4310/commits/37c7e5ca80d9b4335d3f383d9d7f2a49fdba02eb)

These and [Revert "show contact jid in call screen"](https://github.com/iNPUTmice/Conversations/pull/4310/commits/cdfdb49adbcc614a6a98457ebc5971a60ef2c1ab) depend on [Revert "do not restart wakelock if activity is finishing"](https://github.com/iNPUTmice/Conversations/pull/4310/commits/eb4e6f08cee2c56ab4931d588b74a988cd1a74b3) since it brings the `checkMicrophoneAvailabilitySync()` thing _(adds that and modifies `checkMicrophoneAvailability()` and `proposeJingleRtpSession()` as needed)_ which might be easier to cherry pick

**Comment by iNPUTmice** [comment]
2.10.9 will be available on fdroid.

**Pull request closed without merging**
