### PR TITLE
Missed call notifications

### PR DESCRIPTION
**Pull request by dmitry-markin**
Hope this may be helpful

### CODE REVIEW

**Comment by aeab13** [comment]
@iNPUTmice will this PR ever be considered? Being honest, not the PR itself but the feature is something quite simple and useful to be simply ignored.

**Comment by satarsa** [comment]
> @iNPUTmice will this PR ever be considered? Being honest, not the PR itself but the feature is something quite simple and useful to be simply ignored.

I agree, this feature is really useful, if I may vote this PR, please consider it. Thanks.

**Comment by jmencak** [comment]
Thank you Dmitry, works for me fine after rebase!  I'm not `Conversations` developer, but I do appreciate this effort.  Would you be able to rebase?  Perhaps after that the developers would consider this PR?

**Comment by chpio** [comment]
So this has been done 2 years ago and still not merged? How can one even consider a calling app without a missed call notification to be in any way finished?

**Comment by jmencak** [comment]
> So this has been done 2 years ago and still not merged?

It is not exactly surprising.  The PR had no (official) review and what contributor wants to contribute/update their PRs when they are treated like this. To defend the main developer though, he's doing a fantastic job and perhaps this just slipped through his fingers.  What is mind-boggling though, https://github.com/iNPUTmice/Conversations/issues/4122 being closed without any comment whatsoever.

> Is there a fork of conversations with essential features like this one add to it?

I'm not aware of one.  But of course, you're free to fork.  Personally, I just keep updating conversations and adjusting this patch not to conflict.  But yeah, it is extra work, therefore annoying. :)

**Comment by emankced** [comment]
Since the patches are very old there are merge conflicts. I resolved the merge conflicts on my [branch](https://github.com/emankced/Conversations/tree/update_missed_call_notification). Maybe a maintainer can check it out this time, so the PR no longer needs to stall.

**Pull request merged**
