### PR TITLE
preserve new lines when quoting. fixes #3876

### LINKED ISSUE #3876: 'Paste as Quote' strips empty lines
#### General information

* **Version:** 2.8.10+pcr
* **Device:** Pixel 3
* **Android Version:**  Android 11 (stock)
* **Server name:** self hosted
* **Server software:** prosody 0.11.5
* **Installed server modules:** I'd have to look...
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Copy text with empty lines
2. Select 'Paste as Quote'
3. All empty lines are stripped

#### Expected result

If I copy and paste the following text:

```text
This is the first line.

This is the second line.
```

I would expect:

```text
> This is the first line.
>
> This is the second line.
```

#### Actual result

But it actually gets pasted as:

```text
> This is the first line.
> This is the second line.
```

Preserving the empty lines would be nice during paste, especially for multi-paragraph quotes where the empty lines separate the paragraphs.

### PR DESCRIPTION
**Pull request by iNPUTmice**
Please review @agude @licaon-kter  @Millesimus. I have no idea how the current quoting works

### CODE REVIEW

**Comment by agude** [comment]
## Main review

This should fix #3876 because the removed part, `.replaceAll("(\n *){2,}", "\n")` replaces multiple newlines with a single new line, but that means that things like:

> Line 1
>
> Line 2

Which is `Line 1\n\nLine2`. After the substitution this becomes `Line 1\nLine2` which is:

> Line 1
> Line 2

**Comment by licaon-kter** [comment]
Not working for me

Text is
```
Line1 

Line2
```
...copy it, then insert as quote

Old way:
```
| Line1
| Line2
```
...notice the missing empty line

This PR
```
| Line1
Line2
```
...more b0rken :(

**Comment by agude** [comment]
That's odd...

I'm not an Android dev so testing the full app is beyond the scope of my expertise (and my family won't let me acquire such expertise this weekend...), but I can extract the function and test it locally. Let me give that a shot.

**Comment by licaon-kter** [comment]
I can provide a testing APK if you join the support channel.

**Comment by agude** [comment]
Thanks for the offer!

But I don't think that helps in the long run since at that point all I can do is say "Ah yes, it is broken". :-/ Without the ability to modify and recompile the APK I won't be able to help debug.

**Comment by Millesimus** [comment]
Fixed it here: https://github.com/Millesimus/Conv666ations/commits/feature_preserve_new_lines_on_quote
Apparently, we were very thorough in ensuring that empty lines may never be quoted.

Branch also contains a fix w.r.t. nested quotes that I stumbled upon while debugging.

**Comment by iNPUTmice** [comment]
@Millesimus can you PR those fixes?

**Pull request closed without merging**
