### PR TITLE
Fix screen blinking during the call for some Samsung phones

### PR DESCRIPTION
**Pull request by vampik**
Fixed issue #3797

### CODE REVIEW

**Comment by iNPUTmice** [comment]
This leaks the wake lock. 
1. Make audio call.
2. Rotate device.
3. Press home button
4. Move hand over proximity sensor. Screen turns off even though it shouldn’t
5. Hang up call via notification.
6. See that wake lock is still engaged.

**Comment by vampik** [comment]
Yes, reproducible bug :-(

I'll try another solution next week. Unfortunately the buggy Samsung phone is not mine and I have to wait for the next visit to the owner.

**Comment by iNPUTmice** [comment]
Another problem with this approach is that is releases the wake lock if you pull down the notifications / quick settings panel and doesn’t re-acquire it when you push it back up.

**Comment by vampik** [comment]
I've found another buggy Samsung phone in my junk for testing (J5 2016, Android 6) and managed to check the another solution. Works fine for me.
It is a super simple solution and it has no issues with rotation/home button since I've moved lock releasing back to the OnStop().
Please check this out.

**Comment by vampik** [comment]
Btw it also fixes occasional ear taps on screen after the call ending.

**Comment by iNPUTmice** [comment]
> Btw it also fixes occasional ear taps on screen after the call ending.

Yes. I was about to say the same. That’s a pretty neat side effect of using that flag.

Can you confirm that your PR works for multiple moves to ear and back? Meaning will the wake lock be reacquired after the display has been turned off and on again.

**Comment by vampik** [comment]
> Can you confirm that your PR works for multiple moves to ear and back? Meaning will the wake lock be reacquired after the display has been turned off and on again.

Works for me.

**Pull request merged**
